eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    config:
      server:
        git:
          url: https://github.com/PrasadNayak2000/ms-config-server
  application:
    name: config-server

server:
  port: 8888

brahmi: bac